name: formatting jobs
on: push

jobs:

  Checking_black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install black
          black --check .
        
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install pytest
          pytest .
