name: formatting jobs
on: push

jobs:

  Checking_black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install black
          black --check .
        
  Checking_pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        pip install pylint
        pylint --ignore build,.ipynb_checkpoints final_repo_06682
